### ISSUE TITLE
Flameon performance

### ISSUE THREAD

**Issue by gaslit** [DockYard/flame_on#14]
Thanks for the magnificent work done on flameon and my hat off to you for rapidly rectifying the liveview rendering.

But a quick question, does flameon still do not influence the benchmarking because i realize for some endpoints testing using API tools, it appears significantly faster without flameon. With flameon, the extra time taken can be a number of seconds.

If im wrong, please close this and I stand corrected.

Thanks.

**Comment by TheFirstAvenger** [comment]
@gaslit FlameOn uses Erlang tracing, which shouldn't add much overhead if any, especially not seconds worth. How long is the API call taking without Flame On and with Flame On? Is the server at 100% capacity under load while you are tracing, or is this a one-off on an otherwise idle server?

**Comment by gaslit** [comment]
Many thanks. I will monitor. Its roughly 20ms but sometimes appear and sometimes disappears so probably it is not flame_on.
