### ISSUE TITLE
MFA validation does not work for remote nodes

### ISSUE THREAD

**Issue by schrockwell** [DockYard/flame_on#22]
When selecting another node in LiveDashboard, the validations for module/function/arity do not know how to introspect the exports on the non-local node, so the validations will fail if that MFA does not also exist on the local node.

As a workaround, if you define the MFA as a no-op in the local node, the validations will pass and the trace will start on the remote node. So, this does not appear to be a technical limitation, but just a limitation of the validations.

**Comment by TheFirstAvenger** [comment]
Good catch. Yes, we need to run the validations on the target node not necessarily the current node.
