### ISSUE TITLE
Module does not exist

### ISSUE THREAD

**Issue by leoamigood** [DockYard/flame_on#25]
Thank you for updating this lib to LiveView 0.18, trying it for the first time.

Somehow, some modules are not available thru Phoenix LiveDashboard while other are and working as expected.
From what i see there is nothing specific to the working on not found ones.

Any suggestions?

**Comment by TheFirstAvenger** [comment]
@leoamigood I just merged a number of fixes into main. Can you retry with the latest? If you are still having issues, please let me know which modules you are trying to capture that are reporting they do not exist.

**Comment by leoamigood** [comment]
@TheFirstAvenger unless i am doing something wrong with latest `{:flame_on, git: "https://github.com/DockYard/flame_on.git", branch: "main"}`  now i get Module does not exist for the modules that used to work.

**Comment by leoamigood** [comment]
@TheFirstAvenger if you need an example here is the [branch](https://github.com/leoamigood/alternis/tree/flame_on) of my project: with [module that works](https://github.com/leoamigood/alternis/blob/flame_on/lib/alternis/engines/game_engine_impl.ex#L1) and [module that does not](https://github.com/leoamigood/alternis/blob/flame_on/lib/alternis/engines/match_engine_wordle_impl.ex#L1)

Hope that helps.

**Comment by leoamigood** [comment]
@TheFirstAvenger Thank you! Works perfectly!
