### ISSUE TITLE
Trace server overloaded with traces of Jason.Decoder.string

### ISSUE THREAD

**Issue by TheFirstAvenger** [DockYard/flame_on#26]
As discussed in #18, we are experiencing an issue whereby some traces result in 800k+ entries being sent by `:erlang.trace` to our trace server. We were unable to determine when exactly this issue appeared. We downgraded a number of versions and the issue persisted on the project we could reliably reproduce it on, including Jason 1.4 -> 1.0.1, Erlang 25 -> 23. It is possible that this has always been an issue and we just never ran into it, but it is also possible that something in the LIveView upgrade either caused or exacerbated this issue.

**Comment by aselder** [comment]
I'm not sure on the internals of FlameOn, but is it possible to declare certain methods opaque (for instance, once Jason.decode/1 is called, don't track function calls inside that). This would fix this case, as well as allow users to exclude data from flame graphs that they don't care about.

**Comment by TheFirstAvenger** [comment]
Under the hood, we are using [:erlang.trace/3](https://www.erlang.org/doc/man/erlang.html#trace-3), and at first glance I am not seeing a way to exclude certain modules from tracing.

**Comment by TheFirstAvenger** [comment]
@aselder I pushed some updates to the main branch on FlameOn, and Elixir 1.15 and 1.16 have come out since then. Would you be able to see if this issue is still happening for you with main and Elixir 1.16?

**Comment by TheFirstAvenger** [comment]
Closing for now. If you are still able to reproduce this issue on main, please let me know.
