### ISSUE TITLE
How to inspect a phoenix handle_message?

### ISSUE THREAD

**Issue by drathier** [DockYard/flame_on#29]
I can get flame_on to trigger on the default cowboy_handler, but I can't get it to trigger on basically anything else. 

I've tried both erlang and elixir functions. I've looked at the beam file to see if the function names are mangled. No luck. 

Can you or anyone else get it to work on phoenix liveview's `handle_event`? Does it work for anyone else?

**Comment by TheFirstAvenger** [comment]
@drathier could you reply with the exact version of Flame On you are using, and the exact values you are entering in the 4 input boxes on the Flame On page?

**Comment by TheFirstAvenger** [comment]
@drathier I was able to trace the `handle_event` function on the latest code from main:
<img width="1326" alt="Screenshot 2024-06-15 at 12 46 43 PM" src="https://github.com/DockYard/flame_on/assets/8557871/9066e999-34dc-4495-badf-e84ab6aef099">

I will close this for now, if you are still having issues, please reply and we can take a look.
