### ISSUE TITLE
Support LiveView 0.18.X

### ISSUE THREAD

**Issue by davydog187** [DockYard/flame_on#30]
Hello and thanks for the great project!

This issue is to track support for the latest release of `phoenix_live_view`, 0.18.18.

Currently, it is incompatible

```
Because your app depends on flame_on ~> 0.2 which depends on phoenix_live_view ~> 0.17.6, phoenix_live_view ~> 0.17.6 is required.
So, because your app depends on phoenix_live_view ~> 0.18.3, version solving failed.
```

**Comment by TheFirstAvenger** [comment]
@davydog187 we do have support for LV 0.18 in main, however #26 is a real issue that I have not yet been able to resolve and was hoping to figure out before cutting an official hex release. Could you try main in your project and let me know if you run into the same issue outlined in #26? Either way if you could report your findings in that issue, it would be greatly appreciated.

**Comment by davydog187** [comment]
@TheFirstAvenger appreciate it! I'll give it a run as soon as I can and report back

**Comment by davydog187** [comment]
@TheFirstAvenger I was able to get it installed against the main branch. However, when running against the `:cowboy_handler.execute/2` function, it resulted in a lot of spans and crashed the BEAM.

```
[debug] flame_on trace: call {:gen, :"-call/4-fun-0-", 4}, stack_size: 100
[debug] flame_on trace: call {:gen, :do_call, 4}, stack_size: 101
[debug] flame_on trace: call {:erlang, :monitor, 2}, stack_size: 102
[debug] flame_on trace: return_to {:gen, :do_call, 4}, stack_size: 103
[debug] flame_on trace: out {:gen, :do_call, 4}, stack_size: 102
[debug] flame_on trace: in {:gen, :do_call, 4}, stack_size: 103




[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[os_mon] memory supervisor port (memsup): Erlang has closed
[1]    27037 bus error  mix phx.server
```

I believe this may be related to #26. However, running against a smaller function like `Phoenix.Flash.get/2` worked just fine

**Comment by florianb** [comment]
Thank you very much @TheFirstAvenger - i won't be able to verify it before Friday, i hope that's fine?

**Comment by TheFirstAvenger** [comment]
I am going to close this ticket as the original request (0.18) is already in main. If you are still getting the issues you were, please open a new issue with the details.
