### ISSUE TITLE
"Flame On" page not visible in LiveDashboard

### ISSUE THREAD

**Issue by samrat** [DockYard/flame_on#37]
Hi,

I've added `flame_on` as a dependency and added it to my router.ex:

```
live_dashboard "/dashboard",
        metrics: DaymarWeb.Telemetry,
        flame_on: FlameOn.DashboardPage
```

but after restarting the server, I still don't see the page on my LiveDashboard. When I try going directly to `http://localhost:4000/dev/dashboard/flame_on` I get 

```
Phoenix.LiveDashboard.PageNotFound at GET /dev/dashboard/flame_on

unknown page "flame_on"
```

Versions of relevant deps:

```
{:flame_on, "~> 0.6.0"}
{:phoenix_live_view, "~> 0.20.1"},
{:phoenix_live_dashboard, "~> 0.8.2"},
```

**Comment by TheFirstAvenger** [comment]
@samrat I have pushed some changes to main. If you are still having issues with this appearing on your dashboard, can you let me know?

**Comment by TheFirstAvenger** [comment]
Closing for now. If you are still having this issue on the latest main branch, reply and I will reopen.
