### ISSUE TITLE
Capture function calls on remote nodes

### ISSUE THREAD

**Issue by slashmili** [DockYard/flame_on#6]
Hi 👋🏼 

I have a question, I'm trying to run the flame_on on a remote node but it only enables trace on the local host.

1. First run a dashboard on Node called `live`, attached the node my `test` node 
2. Visited dashboard on `live` instance and select `test` node.
3. Started capturing to `Elixir.IO.inspect/1` 
4. Ran `IO.inspect("hello")` on `test` node.
5. Got timeout

![Screenshot 2022-02-28 at 14 24 52](https://user-images.githubusercontent.com/585764/155990759-46116b0e-61cd-415b-9728-563e262bd80c.png)

If I do the same step but run the `IO.inspect("hello")` on `live` node, I get the 🔥 graphs.

Any suggestion or pointer on how can we fix that?

**Comment by TheFirstAvenger** [comment]
@slashmili Yes, currently Flame On runs on the node the LiveView happens to connect to. I am planning on implementing support to honor the LiveDashboard node switcher. If it's ok with you I will use this ticket to track that enhancement.

**Comment by TheFirstAvenger** [comment]
@slashmili v0.4.0 now honors the LiveDashboard node switcher: https://twitter.com/1stAvenger/status/1504568466732376077
