### ISSUE TITLE
Flame On does not display result

### ISSUE THREAD

**Issue by bluzky** [DockYard/flame_on#9]
Hi, I'm testing flame_on on my local server but it doesn't display profiling result and it uses too much memory.

### Dependencies
```
      {:phoenix, "~> 1.6"},
      {:phoenix_ecto, "~> 4.0"},
      {:phoenix_live_dashboard, "~> 0.6.5"},
      {:flame_on, "~> 0.3"},
      {:telemetry_metrics, "~> 0.4"},
      {:telemetry_poller, "~> 0.4"}
```

### Environment
- Macbook M1
- Elixir: 1.13
- Erlang: 24.1.4

**It uses too much memory**
![Screen Shot 2022-03-17 at 10 52 01 AM](https://user-images.githubusercontent.com/6194779/158734290-558ca318-baac-4bc6-91e1-f1b1ec5df69e.png)

**Capturing timeout**
![Screen Shot 2022-03-17 at 10 46 35 AM](https://user-images.githubusercontent.com/6194779/158734373-002c702d-61ae-45aa-be69-7ba30f5acd04.png)

**Some strange output on console**
```
[info] Received unexpected trace event: {:trace_ts, #PID<0.4454.0>, :return_to, {Jason.Encode, :map_naive_loop, 3}, {1647, 489616, 144705}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.4454.0>, :return_to, {Jason.Encode, :map_naive_loop, 3}, {1647, 489616, 144706}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.4454.0>, :gc_minor_start, [wordsize: 2, old_heap_block_size: 196650, heap_block_size: 28690, mbuf_size: 1168, recent_size: 187, stack_size: 155, old_heap_size: 81714, heap_size: 28534, bin_vheap_size: 105, bin_vheap_block_size: 46422, bin_old_vheap_size: 5583, bin_old_vheap_block_size: 46422], {1647, 489616, 145129}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.4454.0>, :gc_minor_end, [wordsize: 28251, old_heap_block_size: 196650, heap_block_size: 28690, mbuf_size: 0, recent_size: 1354, stack_size: 155, old_heap_size: 81811, heap_size: 1354, bin_vheap_size: 12, bin_vheap_block_size: 46422, bin_old_vheap_size: 5619, bin_old_vheap_block_size: 46422], {1647, 489616, 145130}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.4454.0>, :return_to, {Jason.Encode, :map_naive_loop, 3}, {1647, 489616, 145134}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.4454.0>, :return_to, {Jason.Encode, :map_naive_loop, 3}, {1647, 489616, 145135}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.4454.0>, :return_to, {Jason.Encode, :map_naive_loop, 3}, {1647, 489616, 145136}}
```

Do I miss any configuration to make it work?

Thanks

**Comment by gaslit** [comment]
https://github.com/DockYard/flame_on/issues/7

I believe your issue is also related. Maybe you can comment in that issue thread as well so we'll be all kept in the loop. :)

**Comment by TheFirstAvenger** [comment]
@bluzky how large of a call are you profiling? Can you increase the timeout to 60000 and see if it works or if you get different log outputs? The `:gc_` and `:return_to` entries are not problems and can be ignored.  Also can you verify if any .bggg files are generated in your project after running it?

**Comment by TheFirstAvenger** [comment]
@gaslit Can you post any log entries that happen when the bggg file is created successfully (you can omit `:gc_` and `:return_to` lines).

**Comment by bluzky** [comment]
> @bluzky how large of a call are you profiling? Can you increase the timeout to 60000 and see if it works or if you get different log outputs? The `:gc_` and `:return_to` entries are not problems and can be ignored. Also can you verify if any .bggg files are generated in your project after running it?

I tried capturing default `cowboy_handler` and change timeout to 60_000 but it still not display result.
I checked I saw that a `1647593610062327-eflambe-output.bggg` was generated it's only 1.3MB

**Comment by gaslit** [comment]
> > @bluzky how large of a call are you profiling? Can you increase the timeout to 60000 and see if it works or if you get different log outputs? The `:gc_` and `:return_to` entries are not problems and can be ignored. Also can you verify if any .bggg files are generated in your project after running it?
> 
> I tried capturing default `cowboy_handler` and change timeout to 60_000 but it still not display result. I checked I saw that a `1647593610062327-eflambe-output.bggg` was generated it's only 1.3MB

Hi are you able to open it in speedscope.app? Does it render correctly?

I have a suspicion it has to do with the LiveComponent but nothing conclusive despite digging into a local copy of the library.

**Comment by bluzky** [comment]
> Hi are you able to open it in speedscope.app? Does it render correctly?
> 
> I have a suspicion it has to do with the LiveComponent but nothing conclusive despite digging into a local copy of the library.

Thank you for helping.
I create a new Phoenix project and Flame_on works. Maybe there are some issue with my existing umbrella project.
I will investigate more on my project.

**Comment by dvic** [comment]
I'm having the same issue (M1 but no umbrella app), I'm having various unexpected trace events, like

`Received unexpected trace event: {:trace_ts, #PID<0.1073.0>, :return_to, {Enum, :"-map/2-lists^map/1-0-", 2}, {1648, 206716, 484641}}`

Have not yet investigated with a fresh phoenix project.

**Comment by dvic** [comment]
> I'm having the same issue (M1 but no umbrella app), I'm having various unexpected trace events, like
> 
> `Received unexpected trace event: {:trace_ts, #PID<0.1073.0>, :return_to, {Enum, :"-map/2-lists^map/1-0-", 2}, {1648, 206716, 484641}}`
> 
> Have not yet investigated with a fresh phoenix project.

Update: on a fresh phoenix liveview project it works (tracing some dummy liveview mount/3 function). Very weird, the liveview versions are the same.

**Comment by jaimeiniesta** [comment]
I did have the same problem in my app, so I tried with a fresh Phoenix 1.6.6 project. The flame graph is shown but I do see a lot of warnings. This is on an M1 macbook:

```
[info] GET /
[debug] Processing with PentoWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 12ms
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :return_to, {Phoenix.Controller, :render, 3}, {1648, 207183, 933036}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :gc_minor_start, [wordsize: 2, old_heap_block_size: 4185, heap_block_size: 1598, mbuf_size: 24, recent_size: 419, stack_size: 92, old_heap_size: 930, heap_size: 1505, bin_vheap_size: 2, bin_vheap_block_size: 46422, bin_old_vheap_size: 324, bin_old_vheap_block_size: 46422], {1648, 207183, 933141}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :gc_minor_end, [wordsize: 1021, old_heap_block_size: 4185, heap_block_size: 2586, mbuf_size: 0, recent_size: 195, stack_size: 92, old_heap_size: 1243, heap_size: 195, bin_vheap_size: 2, bin_vheap_block_size: 46422, bin_old_vheap_size: 324, bin_old_vheap_block_size: 46422], {1648, 207183, 933154}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :return_to, {Phoenix.Template, :format_encoder, 1}, {1648, 207183, 933252}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :return_to, {Phoenix.HTML, :build_attrs, 1}, {1648, 207183, 935995}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :return_to, {Phoenix.HTML, :build_attrs, 1}, {1648, 207183, 935996}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :gc_minor_start, [wordsize: 3, old_heap_block_size: 4185, heap_block_size: 2586, mbuf_size: 298, recent_size: 195, stack_size: 108, old_heap_size: 1243, heap_size: 2477, bin_vheap_size: 5, bin_vheap_block_size: 46422, bin_old_vheap_size: 324, bin_old_vheap_block_size: 46422], {1648, 207183, 936065}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :gc_minor_end, [wordsize: 2530, old_heap_block_size: 4185, heap_block_size: 4185, mbuf_size: 0, recent_size: 82, stack_size: 108, old_heap_size: 1406, heap_size: 82, bin_vheap_size: 10, bin_vheap_block_size: 46422, bin_old_vheap_size: 325, bin_old_vheap_block_size: 46422], {1648, 207183, 936076}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :return_to, {Phoenix.HTML, :build_attrs, 1}, {1648, 207183, 936217}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :return_to, {Phoenix.HTML, :build_attrs, 1}, {1648, 207183, 936270}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :return_to, {Phoenix.HTML, :build_attrs, 1}, {1648, 207183, 936334}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :return_to, {Phoenix.HTML, :build_attrs, 1}, {1648, 207183, 936491}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :return_to, {Gettext.Compiler, :warn_if_domain_contains_slashes, 1}, {1648, 207183, 936606}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :return_to, {PentoWeb.Gettext, :handle_missing_translation, 4}, {1648, 207183, 936607}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :gc_minor_start, [wordsize: 2, old_heap_block_size: 4185, heap_block_size: 4185, mbuf_size: 24, recent_size: 82, stack_size: 109, old_heap_size: 1406, heap_size: 4076, bin_vheap_size: 291, bin_vheap_block_size: 46422, bin_old_vheap_size: 325, bin_old_vheap_block_size: 46422], {1648, 207183, 936782}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :gc_minor_end, [wordsize: 3767, old_heap_block_size: 4185, heap_block_size: 1598, mbuf_size: 0, recent_size: 261, stack_size: 109, old_heap_size: 1478, heap_size: 261, bin_vheap_size: 7, bin_vheap_block_size: 46422, bin_old_vheap_size: 335, bin_old_vheap_block_size: 46422], {1648, 207183, 936789}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :return_to, {Enum, :any_list, 2}, {1648, 207183, 936831}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :gc_minor_start, [wordsize: 0, old_heap_block_size: 4185, heap_block_size: 1598, mbuf_size: 9, recent_size: 261, stack_size: 127, old_heap_size: 1478, heap_size: 1467, bin_vheap_size: 11, bin_vheap_block_size: 46422, bin_old_vheap_size: 335, bin_old_vheap_block_size: 46422], {1648, 207183, 937007}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :gc_minor_end, [wordsize: 1087, old_heap_block_size: 4185, heap_block_size: 2586, mbuf_size: 0, recent_size: 135, stack_size: 127, old_heap_size: 1732, heap_size: 135, bin_vheap_size: 10, bin_vheap_block_size: 46422, bin_old_vheap_size: 342, bin_old_vheap_block_size: 46422], {1648, 207183, 937013}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :return_to, {Logger.Utils, :truncate_n_list, 3}, {1648, 207183, 937087}}
Successful finished trace
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :gc_minor_start, [wordsize: 2, old_heap_block_size: 4185, heap_block_size: 2586, mbuf_size: 34, recent_size: 135, stack_size: 116, old_heap_size: 1732, heap_size: 2469, bin_vheap_size: 388, bin_vheap_block_size: 46422, bin_old_vheap_size: 342, bin_old_vheap_block_size: 46422], {1648, 207183, 938909}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :gc_minor_end, [wordsize: 2449, old_heap_block_size: 4185, heap_block_size: 4185, mbuf_size: 0, recent_size: 54, stack_size: 116, old_heap_size: 1732, heap_size: 54, bin_vheap_size: 286, bin_vheap_block_size: 46422, bin_old_vheap_size: 342, bin_old_vheap_block_size: 46422], {1648, 207183, 938915}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :return_to, {Enum, :"-map/2-lists^map/1-0-", 2}, {1648, 207183, 939067}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :return_to, {Enum, :"-map/2-lists^map/1-0-", 2}, {1648, 207183, 939068}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :return_to, {Enum, :"-map/2-lists^map/1-0-", 2}, {1648, 207183, 939069}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.825.0>, :return_to, {Enum, :"-map/2-lists^map/1-0-", 2}, {1648, 207183, 939070}}
Output filename: flame_on_output_delete_me/1648207183928419-eflambe-output.bggg
```

![Captura de Pantalla 2022-03-25 a las 12 22 25](https://user-images.githubusercontent.com/2629/160112083-e98ebc69-9e24-4ddd-85b7-b7169bbbac72.png)

**Comment by TheFirstAvenger** [comment]
Thank you everyone for your reports on this issue. Just a heads up that I am currently working on #11 which should either resolve these issues directly or give us the tools to be able to diagnose them. I will return to check with you all on this issue once that work is complete.

**Comment by TheFirstAvenger** [comment]
@bluzky @jaimeiniesta @dvic @gaslit I have a PR (#12) up for the engine rewrite. If you have a chance, could you update your deps and let me know if you have success on the new branch?

```elixir
      {:flame_on, github: "DockYard/flame_on", ref: "mb-engine-rewrite"},
```

**Comment by dvic** [comment]
It works for my usecase without any errors! Niceeee 👍

**Comment by gaslit** [comment]
Superb. Works perfectly. Many thanks for your hard work.

Quick question: Is it possible that you do not delete the generated bggg files as having a local copy will be tremendously useful. For simplicity, you can select the most recent one in the directory for rendering. I doubt many will object.

Thank you for your kind consideration.

**Comment by jaimeiniesta** [comment]
Thanks @TheFirstAvenger - it works much better now, I don't see any warnings when profiling a controller.

However I see crashes when profiling one of our LiveViews. It works with other views, but it crashes on this one with this:

https://gist.github.com/jaimeiniesta/0fc76270edfa4d39b6a147e1f79ef76f

**Comment by TheFirstAvenger** [comment]
@gaslit Good question. With the new engine, there is no `.bggg` file. In the old engine, eFlambe would capture the trace and generate the .bggg file, then FlameOn would read, parse, and display the data from the file. The new engine skips this altogether and captures the data directly from the trace. I have added #13 as an enhancement request to generate a .bggg file from a Flame On capture. I will tackle that once the engine rewrite is released.

**Comment by TheFirstAvenger** [comment]
@jaimeiniesta Thanks for the issue report. I have pushed a fix to the branch that should resolve that error. Please update and let me know if that specific LiveView now renders correctly.

**Comment by jaimeiniesta** [comment]
@TheFirstAvenger thanks for the update! That error is now gone, but now I see a different error, I've added it as `crash2.txt` in the gist.

**Comment by jaimeiniesta** [comment]
@TheFirstAvenger sure, I added it as `crash3.txt` in the gist. It was a huge log, I just pasted the latest lines.

**Comment by TheFirstAvenger** [comment]
@jaimeiniesta Ok try now. `:set_on_spawn` was enabled, causing tracing to happen in secondary processes, which broke the stack, as return_to's didn't match in linear order with calls. I disabled it, which means you will only see a flamegraph for the primary process (and a `:sleep` block if it is waiting on a `receive`). If we do decide to do something with graphing secondary processes, it will need a design pass to architect it in a useful way (if that is even possible with a flamegraph... 🤔 ).

**Comment by jaimeiniesta** [comment]
@TheFirstAvenger hey thanks, it now works! This live view doesn't make it crash anymore. 🚀
